name: Validate servers
on: [push, pull_request]

jobs:
  verify-servers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout from GitHub

      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: servers.schema.json
          INPUT_JSONS: servers.json
